version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2-browsers
    working_directory: ~/project/
    steps:
      - checkout
      - run:
          name: Install npm modules
          command: npm i

      - run:
          name: Run test cases
          command: npm run test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
